---
region: 'us-east-1'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

admin_public_gpg_key_path: "%{cwd}/config/secrets/admin/gpg.public"
admin_private_gpg_key_path: "%{cwd}/config/secrets/admin/gpg.private"
